name: 'Hello World'
description: 'Greet someone'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Setup OPA
      id: setup-opa
      run: install-opa.sh
      shell: bash
    - name: Bye
      run: echo "Goodbye!"
      shell: bash
